#!/usr/bin/env bash
# Bash script that cofigures Nginx
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
sudo chown -R "$USER":"$USER" /var/www/html && sudo chmod -R 755 /var/www
sudo sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
