#!/usr/bin/env bash
# Bash script that cofigures Nginx
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World' >> /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html && sudo chmod -R 755 /var/www
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
