#!/usr/bin/env bash
# Update the system
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
config_string=\
"
frontend server-frontend
    bind *:80
    mode http
    default_backend server_backend

backend server_backend
    balance roundrobin
    server 197107-web-01 34.232.77.180:80 check
    server 197107-web-02 54.236.16.94:80 check
"
echo "$config_string" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy init script
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
